app:
  build: .
  ports:
   - 8080:8080
  environment:
    DATABASE_URL: postgres://admin:admin@db:5432/piecemeal
  links:
   - db

db:
  image: postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: admin
    POSTGRES_DB: piecemeal
